### ISSUE TITLE
Install chamferdist error

### ISSUE THREAD

**Issue by djFatNerd** [samxuxiang/BrepGen#13]
Hi, I setup the environment as the requirements with pytorch=2.2, cuda=11.8, and python = 3.9. However, both pip install chamferdist and building from source gives me the following error:

python setup.py install
running install
/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing chamferdist.egg-info/PKG-INFO
writing dependency_links to chamferdist.egg-info/dependency_links.txt
writing requirements to chamferdist.egg-info/requires.txt
writing top-level names to chamferdist.egg-info/top_level.txt
reading manifest file 'chamferdist.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'chamferdist.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying chamferdist/version.py -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/chamfer.py -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/__init__.py -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/knn.cu -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/dispatch.cuh -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/mink.cuh -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/index_utils.cuh -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/knn.h -> build/lib.linux-x86_64-cpython-39/chamferdist
copying chamferdist/cutils.h -> build/lib.linux-x86_64-cpython-39/chamferdist
running build_ext
/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'chamferdist._C' extension
Emitting ninja build file /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /data/jd_data/miniconda3/envs/brepgen/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/chamferdist/knn.o.d -DWITH_CUDA -Ichamferdist -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/TH -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/THC -I/data/jd_data/miniconda3/envs/brepgen/include -I/data/jd_data/miniconda3/envs/brepgen/include/python3.9 -c -c /data/jd_data/chamferdist/chamferdist/knn.cu -o /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/chamferdist/knn.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
FAILED: /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/chamferdist/knn.o 
/data/jd_data/miniconda3/envs/brepgen/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/chamferdist/knn.o.d -DWITH_CUDA -Ichamferdist -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/TH -I/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/THC -I/data/jd_data/miniconda3/envs/brepgen/include -I/data/jd_data/miniconda3/envs/brepgen/include/python3.9 -c -c /data/jd_data/chamferdist/chamferdist/knn.cu -o /data/jd_data/chamferdist/build/temp.linux-x86_64-cpython-39/chamferdist/knn.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
In file included from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/c10/core/ScalarType.h:3,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/c10/core/ScalarTypeToTypeMeta.h:3,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h:6,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/c10/core/GeneratorImpl.h:8,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/ATen/core/Generator.h:22,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/ATen/Context.h:3,
                 from /data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /data/jd_data/chamferdist/chamferdist/knn.cu:3:
/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/include/c10/util/BFloat16.h:11:10: fatal error: cuda_bf16.h: **No such file or directory
 #include <cuda_bf16.h>
          ^~~~~~~~~~~~~**
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/jd_data/chamferdist/setup.py", line 76, in <module>
    setup(
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
    build_ext.build_extensions(self)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/data/jd_data/miniconda3/envs/brepgen/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

I referred to the original chamferdist repo but couldn't find any possible solution either, may I ask if u know how to resolve this? Or is there any alternative dependencies combination that you have tested and would work? 

Thank you.

**Comment by samxuxiang** [comment]
Hi @djFatNerd , can you try using `setuptools==69.5.1` and then `python -m pip install chamferdist==1.0.3` ? Hopefully this resolves the issue.

**Comment by djFatNerd** [comment]
Thank you, but I still got the same error after setting setuptools and chamferdist version manually.
![image](https://github.com/samxuxiang/BrepGen/assets/44420977/38d57cd5-356e-4d3d-ad8c-9ddb18e35b0f)
![image](https://github.com/samxuxiang/BrepGen/assets/44420977/37e4fe1a-81b5-4ff7-b7c4-da5d8ac5c9f0)

**Comment by harunijaz** [comment]
Hi, @djFatNerd , I realize it’s a bit late to respond, but this might help others avoid the issue. Setting up the environment with python=3.10.13, torch=2.4.0+cu124, and nvcc --version=12.4 (or any version above 12) worked smoothly for me.

**Comment by harunijaz** [comment]
Hi, @djFatNerd  , I realize it’s a bit late to respond, but this might help others avoid the issue. Setting up the environment with python=3.10.13, torch=2.4.0+cu124, and nvcc --version=12.4 (or any version above 12) worked smoothly for me.
