### ISSUE TITLE
OCCWL is Installed but still get this error, I using the Furniture dataset

### ISSUE THREAD

**Issue by adeerkhan** [samxuxiang/BrepGen#6]
I solved the OCCWL issue as now I am working in Conda environment, but now I get this error:
```
:~/Github/BrepGen/data_process$ sh process.sh
Traceback (most recent call last):
  File "/home/adeer/Github/BrepGen/data_process/process_brep.py", line 6, in <module>
    from convert_utils import *
  File "/home/adeer/Github/BrepGen/data_process/convert_utils.py", line 5, in <module>
    from occwl.uvgrid import ugrid, uvgrid
  File "/home/adeer/miniconda3/envs/brepgen_env/lib/python3.9/site-packages/occwl/uvgrid.py", line 4, in <module>
    from occwl.face import Face
  File "/home/adeer/miniconda3/envs/brepgen_env/lib/python3.9/site-packages/occwl/face.py", line 4, in <module>
    from deprecate import deprecated
ModuleNotFoundError: No module named 'deprecate'
```

**Comment by samxuxiang** [comment]
Hi @adeerkhan , you can try [`pip install deprecate`](https://pypi.org/project/deprecate/). Hope this works.
